### ISSUE TITLE
是否支持最新版本1.3.5 

### ISSUE THREAD

**Issue by yuedingwangji** [MuWinds/fakelocation_sever_docker#1]
请问是否支持最新版本1.3.5 ，
还有，请问如何查看日志

**Comment by MuWinds** [comment]
不支持的，1.3.3+官方就加SSL验证了
查看日志：容器挂载对应目录就能看了

**Comment by yuedingwangji** [comment]
> 不支持的，1.3.3+官方就加SSL验证了 查看日志：容器挂载对应目录就能看了

域名没变的胡， 加了ssl 的话，给这个服务加个ssl 配置，手机在信任对应的ssl证书，是否就可以啦

**Comment by MuWinds** [comment]
> > 不支持的，1.3.3+官方就加SSL验证了 查看日志：容器挂载对应目录就能看了
> 
> 域名没变的胡， 加了ssl 的话，给这个服务加个ssl 配置，手机在信任对应的ssl证书，是否就可以啦

可以的，但是fake location的功能越更新越少，而且明确不支持校园跑，所以也就停留在1.3.2
